### PR TITLE
Release 1.0.0; update README; fix GitHub actions

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by smortex — APPROVED** [review]
Looks like i already saw similar changes… I assume they where automated by modulesync or something similar?

**Comment by bastelfreak** [comment]
you mean the old github actions? Puppetlabs added them before they migrated the repository. We've some templates at https://github.com/voxpupuli/puppet-lint_modulesync_configs. They are desinged for puppet-lint specific gems, but work in most cases also for other gems.

**Comment by root-expert** [comment]
Seems the release failed for this one @bastelfreak

**Comment by bastelfreak** [comment]
Yes, we currently don't have permissions on rubygems, I am in contact with Puppet so they fix it.

**Pull request merged**
